#!/bin/bash

if [ $# -lt 3 ]; then
    echo "usage: juncs2seq fastafile bases repeatmask"
    echo "bases: bases to keep on each side of splice junction"
    echo "repeatmask: 0 to keep repeats, 1 to ignore junctions with any repeats in them"
    echo "example: juncs2seq rn4.fa 25 1"
    echo "This will take a juncs file from stdin, look up the sequences in rn4.fa, and
output 50 bases which span the junction, as long as a repeat is not found,"

    exit 1
fi
i=0
while read -ra array; do
    # skip the first line as it is a header line
    if [ $i -eq 0 ]; then
	i=$(($i+1))
	continue
    fi
    lquery=${array[0]}:$((${array[1]}-$2))-${array[1]}
    rquery=${array[0]}:${array[2]}-$((${array[2]}+$2))
    lseq=$(samtools faidx $1 $lquery | sed 1d | tr -d "\n")
    rseq=$(samtools faidx $1 $rquery | sed 1d | tr -d "\n")
    seq=${lseq}${rseq}
    # skip repeats
    if [ $3 -eq 1 ]; then
	check=$(echo $seq | sed -n /[[:lower:]]/p)
	if [ "$check" == '' ]; then
	    echo -e ">${array[3]}\n${seq}"
	fi
    else
	echo -e ">${array[3]}\n${seq}"
    fi

done